config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {
      :sign_in => 'users/registrations'
  }

  resources :payments

  get 'payments/index'
  root to: 'payments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  has_many :payments

  attr_accessor :login

  validates :username, length: {minimum: 3}
  validates :username, :uniqueness => false
  validates :email, :uniqueness => false

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @payment = Payment.new
    @payments = Payment.order('ends_at ASC').page(params[:page]).per(5)
  end

  def create

    if Payment.all.present?
      @last_payment = Payment.last.ends_at

      if @last_payment.day < 15
        @payment = Payment.new(starts_at: @last_payment.next_day,
                               ends_at: @last_payment + 15.day,
                               user_id: current_user.id)
      else
        @payment = Payment.new(starts_at: @last_payment.next_day,
                               ends_at: @last_payment.next_month - 15.day,
                               user_id: current_user.id)
      end
    else
      @payment = Payment.new(starts_at: Date.new(2016, 01, 5),
                             ends_at: Date.new(2016, 01, 19),
                             user_id: current_user.id)
    end

    if @payment.save
      redirect_to payments_path
    else
      render :new
    end
  end

  def destroy
    @payment = Payment.find(params[:id])

    @payment.destroy
    redirect_to payments_path
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_filter :authenticate_user!, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  #
  # protected
  #
  # def authenticate_user!
  #   if user_signed_in?
  #     super
  #   else
  #     redirect_to login_path, :notice => 'if you want to add a notice'
      ## if you want render 404 page
      ## render :file => File.join(Rails.root, 'public/404'), :formats => [:html], :status => 404, :layout => false
    # end
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApplicationTest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script type="text/javascript">
      function button_click() {
        toastr.success("Payment successfully created");
      }
    </script>
  </head>
  <body>
    <header>
      <% if user_signed_in? %>
        <!--Меню зарегистрированного пользователя-->
        <div class="menu_register">
          <h1>Application</h1>
          <ul>
            <li><%= link_to 'Main page'%></li>
            <li><%= link_to 'Payments', payments_path %></li>
            <li class="logout">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete%> (<%= current_user.email %>)
            </li>
          </ul>
        </div>
      <% else %>
        <!--Меню не зарегистрированного пользователя-->
        <div class="menu_login">
          <p> Welcome to Application. Please login <p>
        </div>
      <% end %>
    </header>
    <div class="info">
      <li id="notice" class="notice"><%= notice %></li>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>

app/views/payments/index.html.erb
<div class="container">

  <!-- Создание платежа -->
  <div class="button_create">
    <%= form_for(@payment) do |f| %>
        <%= f.submit 'Create Payment', :class=> 'btn btn-info', :onclick=> 'button_click()' %>
  <% end %>
  </div>

  <div class="paymant_info">
    <% if @payments.present? %>
      <!-- Начальная и конечная дата -->
      <div class="paymants_from">
      <%= raw "Paymants from <b>#{@payments.first.starts_at.strftime("%b %e, %Y")}</b>
          to <b>#{@payments.last.ends_at.strftime("%b %e, %Y")}</b>" %>
      </div>

      <!-- Таблица с выплатами -->
      <table class="table table-striped" width="400px">
        <thead>
          <tr>
            <td> # </td>
            <td>Dates </td>
            <td>Creator </td>
            <td>Actions </td>
          </tr>
        </thead>
        <tbody>
        <% if @payments.present? %>
          <% @payments.each do |date| %>
            <tr>
              <td class="num"></td>
              <td><%= date.starts_at.strftime("%b %e, %Y") %> - <%= date.ends_at.strftime("%b %e, %Y") %></td>
              <td><%= date.user.email %>  </td>
              <td>
                <% if current_user.email == date.user.email%>
                  <%= link_to 'Delete', payment_path(date), method: :delete, data: { confirm: 'Delete?' },
                              :class=> 'btn btn-danger btn-xs' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
        </tbody>
      </table>
      <!-- Нумерация строк в таблице -->
        <script>
          $('.table tbody tr').each(function(i) {
              var number = i + 1;
              $(this).find('td:first').text(number);
          });
      </script>
    <% else %>
        <p> No data on payments </p>
    <% end %>
    <%= paginate @payments %>

  </div>
</div>